In [1]:
import pandas as pd
from unidecode import unidecode

# Load your dataset
df_norm = pd.read_csv('Raw/nba_normal_scorers.csv')
df_out = pd.read_csv('Raw/nba_high_scorers_outliers.csv')

# Step 1: Identify players who have a '2TM' row
players_with_2tm_norm = df_norm[df_norm['Team'] == '2TM']['Player'].unique()
players_with_2tm_out = df_out[df_out['Team'] == '2TM']['Player'].unique()

# Step 2: Keep only:
# - rows where Team == '2TM'
# - OR rows where the player does not appear in the 2TM list
df_filtered_norm = df_norm[(df_norm['Team'] == '2TM') | (~df_norm['Player'].isin(players_with_2tm_norm))]
df_filtered_out = df_out[(df_out['Team'] == '2TM') | (~df_out['Player'].isin(players_with_2tm_out))]

# Reset index
df_filtered_norm = df_filtered_norm.reset_index(drop=True)
df_filtered_out = df_filtered_out.reset_index(drop=True)

In [2]:
df_filtered_norm

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year,AllStarSelection
0,17.0,Jayson Tatum,21.0,BOS,PF,66.0,66.0,34.3,8.4,18.6,...,7.0,3.0,1.4,0.9,2.3,2.1,23.4,"MVP-12,AS,NBA3",2020,1
1,18.0,D'Angelo Russell,23.0,2TM,PG,45.0,45.0,32.3,8.0,18.8,...,3.9,6.3,1.1,0.3,3.3,1.9,23.1,NaN,2020,1
2,19.0,Joel Embiid,25.0,PHI,C,51.0,51.0,29.5,7.5,15.7,...,11.6,3.0,0.9,1.3,3.1,3.4,23.0,AS,2020,1
3,21.0,Zion Williamson,19.0,NOP,PF,24.0,24.0,27.8,8.8,15.0,...,6.3,2.1,0.7,0.4,2.5,1.8,22.5,ROY-3,2020,1
4,22.0,CJ McCollum,28.0,POR,SG,70.0,70.0,36.5,8.7,19.4,...,4.2,4.4,0.8,0.6,1.8,2.6,22.2,NaN,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2307,562.0,Jesse Edwards,24.0,MIN,C,2.0,0.0,2.5,0.0,0.0,...,0.0,0.5,0.0,0.0,0.0,1.0,0.0,NaN,2025,0
2308,565.0,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,1.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025,0
2309,566.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2025,0
2310,567.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,1.0,0.0,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025,0
2311,568.0,Isaiah Stevens,24.0,MIA,PG,3.0,0.0,2.0,0.0,0.7,...,0.7,0.0,0.3,0.0,0.0,0.0,0.0,NaN,2025,0

In [3]:
df_filtered_out

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year,AllStarSelection
0,2.0,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,...,4.2,6.1,1.2,0.4,3.4,2.2,30.5,NaN,2020,1
1,3.0,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,...,4.3,8.0,1.1,0.3,2.9,1.7,30.0,"MVP-8,AS,NBA2",2020,1
2,4.0,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,...,4.3,9.3,1.1,0.1,4.8,1.7,29.6,AS,2020,1
3,5.0,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,...,13.6,5.6,1.0,1.0,3.7,3.1,29.5,"MVP-1,DPOY-1,AS,NBA1,DEF1",2020,1
4,8.0,Russell Westbrook,31.0,HOU,PG,57.0,57.0,35.9,10.6,22.5,...,7.9,7.0,1.6,0.4,4.5,3.5,27.2,"AS,NBA3",2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,26.0,Tyler Herro,25.0,MIA,SG,77.0,77.0,35.4,8.5,17.9,...,5.2,5.5,0.9,0.2,2.6,1.1,23.9,NaN,2025,1
139,27.0,Joel Embiid,30.0,PHI,C,19.0,19.0,30.2,7.4,16.6,...,8.2,4.5,0.7,0.9,3.3,2.2,23.8,NaN,2025,1
140,28.0,De'Aaron Fox,27.0,2TM,PG,62.0,62.0,36.1,8.7,18.8,...,4.8,6.3,1.5,0.4,2.8,2.6,23.5,NaN,2025,1
141,29.0,Zach LaVine,29.0,2TM,SF,74.0,74.0,35.2,8.4,16.5,...,4.3,4.2,0.8,0.2,2.8,1.6,23.3,NaN,2025,1
142,30.0,Ja Morant,25.0,MEM,PG,50.0,50.0,30.4,8.1,17.8,...,4.1,7.3,1.2,0.2,3.7,2.3,23.2,NaN,2025,1

Combine salary

In [4]:
df_salary = pd.read_csv('Raw/nba_player_salaries_by_year.csv')
df_salary

      Year              Player         Team      Salary
0     2020       Stephen Curry  $40,231,758  49346703.0
1     2020   Russell Westbrook  $38,506,482  47230546.0
2     2020          Chris Paul  $38,506,482  47230546.0
3     2020        James Harden  $38,199,000  46853401.0
4     2020           John Wall  $38,199,000  46853401.0
...    ...                 ...          ...         ...
2927  2024      Jalen Crutcher      $64,343     66254.0
2928  2024  Izaiah Brockington      $64,343     66254.0
2929  2024      Taevion Kinsey      $64,343     66254.0
2930  2024       Edmond Sumner      $40,459     41661.0
2931  2024        Kaiser Gates      $35,389     36440.0

[2932 rows x 4 columns]

In [5]:
for df in (df_filtered_norm, df_filtered_out, df_salary):
    df['Player'] = df['Player'].astype(str).apply(lambda x: unidecode(x).strip())
    df['Year']   = df['Year'].astype(int)

# 3. Merge Salary (keep only the numeric Salary column from df_sal)
salary_cols = ['Player', 'Year', 'Salary']
df_norm_merged = pd.merge(df_filtered_norm, df_salary[salary_cols], on=['Player', 'Year'], how='left')
df_out_merged  = pd.merge(df_filtered_out,  df_salary[salary_cols], on=['Player', 'Year'], how='left')

In [7]:
df_norm_merged

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Awards,Year,AllStarSelection,Salary
0,17.0,Jayson Tatum,21.0,BOS,PF,66.0,66.0,34.3,8.4,18.6,...,3.0,1.4,0.9,2.3,2.1,23.4,"MVP-12,AS,NBA3",2020,1,9603972.0
1,18.0,D'Angelo Russell,23.0,2TM,PG,45.0,45.0,32.3,8.0,18.8,...,6.3,1.1,0.3,3.3,1.9,23.1,NaN,2020,1,33466715.0
2,19.0,Joel Embiid,25.0,PHI,C,51.0,51.0,29.5,7.5,15.7,...,3.0,0.9,1.3,3.1,3.4,23.0,AS,2020,1,33736104.0
3,21.0,Zion Williamson,19.0,NOP,PF,24.0,24.0,27.8,8.8,15.0,...,2.1,0.7,0.4,2.5,1.8,22.5,ROY-3,2020,1,11968094.0
4,22.0,CJ McCollum,28.0,POR,SG,70.0,70.0,36.5,8.7,19.4,...,4.4,0.8,0.6,1.8,2.6,22.2,NaN,2020,1,33800289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2307,562.0,Jesse Edwards,24.0,MIN,C,2.0,0.0,2.5,0.0,0.0,...,0.5,0.0,0.0,0.0,1.0,0.0,NaN,2025,0,NaN
2308,565.0,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025,0,NaN
2309,566.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2025,0,NaN
2310,567.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,1.0,0.0,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2025,0,NaN
2311,568.0,Isaiah Stevens,24.0,MIA,PG,3.0,0.0,2.0,0.0,0.7,...,0.0,0.3,0.0,0.0,0.0,0.0,NaN,2025,0,NaN

In [8]:
df_out_merged

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,Awards,Year,AllStarSelection,Salary
0,2.0,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,...,6.1,1.2,0.4,3.4,2.2,30.5,NaN,2020,1,33231237.0
1,3.0,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,...,8.0,1.1,0.3,2.9,1.7,30.0,"MVP-8,AS,NBA2",2020,1,36554362.0
2,4.0,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,...,9.3,1.1,0.1,4.8,1.7,29.6,AS,2020,1,7694216.0
3,5.0,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,...,5.6,1.0,1.0,3.7,3.1,29.5,"MVP-1,DPOY-1,AS,NBA1,DEF1",2020,1,31697642.0
4,8.0,Russell Westbrook,31.0,HOU,PG,57.0,57.0,35.9,10.6,22.5,...,7.0,1.6,0.4,4.5,3.5,27.2,"AS,NBA3",2020,1,47230546.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,26.0,Tyler Herro,25.0,MIA,SG,77.0,77.0,35.4,8.5,17.9,...,5.5,0.9,0.2,2.6,1.1,23.9,NaN,2025,1,NaN
139,27.0,Joel Embiid,30.0,PHI,C,19.0,19.0,30.2,7.4,16.6,...,4.5,0.7,0.9,3.3,2.2,23.8,NaN,2025,1,NaN
140,28.0,De'Aaron Fox,27.0,2TM,PG,62.0,62.0,36.1,8.7,18.8,...,6.3,1.5,0.4,2.8,2.6,23.5,NaN,2025,1,NaN
141,29.0,Zach LaVine,29.0,2TM,SF,74.0,74.0,35.2,8.4,16.5,...,4.2,0.8,0.2,2.8,1.6,23.3,NaN,2025,1,NaN
142,30.0,Ja Morant,25.0,MEM,PG,50.0,50.0,30.4,8.1,17.8,...,7.3,1.2,0.2,3.7,2.3,23.2,NaN,2025,1,NaN

In [10]:
# Save the filtered dataset

# Separate data for the year 2025
df_norm_2025 = df_norm_merged[df_norm_merged['Year'] == 2025].drop(columns=['Salary'])
df_out_2025 = df_out_merged[df_out_merged['Year'] == 2025].drop(columns=['Salary'])

# Save the 2025 data separately
df_norm_2025.to_csv('Processed/nba_normal_scorers_2025.csv', index=False)
df_out_2025.to_csv('Processed/nba_high_scorers_outliers_2025.csv', index=False)

# Remove salary for the year 2025 from the original datasets
df_norm_merged = df_norm_merged[df_norm_merged['Year'] != 2025]
df_out_merged = df_out_merged[df_out_merged['Year'] != 2025]

df_norm_merged.to_csv('Processed/nba_normal_scorers_filtered.csv', index=False)
df_out_merged.to_csv('Processed/nba_high_scorers_outliers_filtered.csv', index=False)